services:
  langgraph-redis:
    image: redis:6
    container_name: turodesk_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 1s
      retries: 5

  # Postgres removidos

  langgraph-api:
    image: ${IMAGE_NAME:-busybox}
    container_name: turodesk_langgraph_api
    ports:
      - "8123:8000"
    depends_on:
      langgraph-redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      REDIS_URI: ${REDIS_URI:-redis://langgraph-redis:6379}
      # DATABASE_URI e MEM_DATABASE_URI removidas

volumes:


